# Generated by Django 4.1.1 on 2022-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonemodel",
            name="image",
            field=models.ImageField(default="no_image.png", upload_to=""),
        ),
    ]
