# Generated by Django 4.1.1 on 2022-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0006_alter_phonemodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonemodel",
            name="image",
            field=models.ImageField(
                default="no_image.png", upload_to="media/model-image"
            ),
        ),
    ]
